source "http://api.berkshelf.com"  
cookbook 'apt'  
cookbook 'ubuntu-change-source-list', github: "ywjno/ubuntu-change-source-list"
cookbook 'gengine', github: "manabuishii/gengine-chef-cookbook"
cookbook 'hostsfile'
#metadata
