source "http://api.berkshelf.com"  
#cookbook 'apt'  
cookbook 'yum'  
#cookbook 'ubuntu-change-source-list', github: "ywjno/ubuntu-change-source-list"
cookbook 'gengine', github: "manabuishii/gengine-chef-cookbook"
#metadata
cookbook 'hostsfile'
